import type { DashboardData } from "./types";

const now = new Date("2026-07-24T10:58:00+07:00");

export const demoData: DashboardData = {
  mode: "demo",
  todayMessageCount: 186,
  unresolvedCount: 3,
  aiQueueNow: 7,
  aiSuccessRate: 84,
  averageLatencyMs: 8400,
  oldestUnresolvedMinutes: 7,
  serviceStatus: [
    { service: "LINE", status: "ok", detail: "รับข้อความล่าสุด 10:58 น." },
    { service: "Hermes", status: "ok", detail: "พร้อมทำงาน 2 ตัว" },
    { service: "ฐานความรู้", status: "ok", detail: "พร้อมใช้" },
    { service: "สำรองข้อมูล", status: "ok", detail: "สำเร็จเมื่อ 02:00 น." },
  ],
  customers: [
    {
      id: "customer-1",
      name: "สมชาย",
      phone: "089-555-0121",
      province: "สุพรรณบุรี",
      district: "สองพี่น้อง",
      lineUserId: "U00000000000000000000000000000001",
      lineDisplayName: "Somchai Farm",
      crops: ["ข้าว", "อ้อย"],
      facts: [
        { type: "จังหวัด", value: "สุพรรณบุรี", confidence: 0.92 },
        { type: "พืชที่ปลูก", value: "ข้าว, อ้อย", confidence: 0.88 },
      ],
      tags: ["ลูกค้าเดิม", "รอแอดมิน"],
      lastContactAt: now.toISOString(),
      status: "active",
    },
    {
      id: "customer-2",
      name: "ป้าละไม",
      phone: "ไม่พบเบอร์",
      province: "นครราชสีมา",
      district: "ปักธงชัย",
      lineUserId: "U00000000000000000000000000000002",
      lineDisplayName: "Lamai",
      crops: ["มันสำปะหลัง"],
      facts: [
        { type: "จังหวัด", value: "นครราชสีมา", confidence: 0.86 },
        { type: "พืชที่ปลูก", value: "มันสำปะหลัง", confidence: 0.9 },
      ],
      tags: ["ถามโรคพืช"],
      lastContactAt: new Date(now.getTime() - 18 * 60_000).toISOString(),
      status: "active",
    },
  ],
  conversations: [
    {
      id: "conversation-1",
      customerId: "customer-1",
      customerName: "สมชาย",
      lineUserId: "U00000000000000000000000000000001",
      province: "สุพรรณบุรี",
      crops: ["ข้าว", "อ้อย"],
      status: "open",
      mode: "bot",
      assignedAdminId: null,
      manualUntil: null,
      version: 7,
      unreadCount: 2,
      lastMessageAt: now.toISOString(),
      lastText: "ราคาจับซื้อทุเรียนภาคใต้เท่าไหร่",
      risk: "urgent",
      messages: [
        {
          id: "message-1",
          direction: "inbound",
          senderType: "customer",
          text: "ราคาจับซื้อทุเรียนภาคใต้เท่าไหร่",
          createdAt: now.toISOString(),
          deliveryStatus: "received",
        },
        {
          id: "message-2",
          direction: "outbound",
          senderType: "bot",
          text: "ระบบขัดข้อง ลองใหม่อีกครั้ง",
          createdAt: new Date(now.getTime() + 10_000).toISOString(),
          deliveryStatus: "sent",
        },
      ],
    },
    {
      id: "conversation-2",
      customerId: "customer-2",
      customerName: "ป้าละไม",
      lineUserId: "U00000000000000000000000000000002",
      province: "นครราชสีมา",
      crops: ["มันสำปะหลัง"],
      status: "open",
      mode: "manual",
      assignedAdminId: "demo-admin",
      manualUntil: new Date(now.getTime() + 24 * 60_000).toISOString(),
      version: 4,
      unreadCount: 1,
      lastMessageAt: new Date(now.getTime() - 7 * 60_000).toISOString(),
      lastText: "ใบมันสำปะหลังเหลือง ควรใช้ตัวไหน",
      risk: "watch",
      messages: [
        {
          id: "message-3",
          direction: "inbound",
          senderType: "customer",
          text: "ใบมันสำปะหลังเหลือง ควรใช้ตัวไหน",
          createdAt: new Date(now.getTime() - 7 * 60_000).toISOString(),
          deliveryStatus: "received",
        },
      ],
    },
  ],
  followUps: [
    {
      id: "task-1",
      customerId: "customer-1",
      customerName: "สมชาย",
      title: "โทรกลับเรื่องสูตรใช้หลังฝนตก",
      status: "open",
      dueAt: now.toISOString(),
    },
    {
      id: "task-2",
      customerId: "customer-2",
      customerName: "ป้าละไม",
      title: "ติดตามอาการใบเหลืองหลังใช้สินค้า",
      status: "open",
      dueAt: new Date(now.getTime() + 2 * 60 * 60_000).toISOString(),
    },
  ],
};

export const emptyLiveData: DashboardData = {
  mode: "live",
  todayMessageCount: 0,
  unresolvedCount: 0,
  aiQueueNow: 0,
  aiSuccessRate: 0,
  averageLatencyMs: null,
  oldestUnresolvedMinutes: null,
  serviceStatus: [],
  customers: [],
  conversations: [],
  followUps: [],
};
